INSERT 
	INTO 
		STATUS(NOME)
	VALUES
		("OK"),
		("AGUARDANDO PAGAMENTO"),
		("CANCELADO"),
		("ADIADO"),
		("ESTORNADO"),
		("QUEBRADO"),
		("FATURADO"),
		("AGUARDANDO COMPENSAÇÃO"),
		("CONFIRMADO"),
		("DESATIVADO"),
		("SUSPENSO"),
		("AGUARDANDO LIMPEZA"),
		("LIMPANDO");

INSERT
	INTO
		PROFISSAO(NOME)
	VALUES
		("MÉDICO"),
		("PROFESSOR"),
		("ANALISTA DE SISTEMAS"),
		("PROGRAMADOR"),
		("REI DO CAMAROTE"),
		("NULO");

INSERT
	INTO
		SEXO(NOME)
	VALUES
		("MASCULINO"),
		("FEMININO"),
		("INTERSEX"),
		("ALIEN"),
		("OPTIMUS PRIME");

INSERT
	INTO
		PESSOA_TIPO(NOME)
	VALUES
		("CLIENTE"),
		("FUNCIONÁRIO CLT"),
		("FUNCIONÁRIO PJ"),
		("PRESTADOR DE SERVIÇOS"),
		("VISITANTE"),
		("CONVIDADO");

INSERT
	INTO
		ORIGEM(NOME)
	VALUES
		("BAR"),
		("RESTAURANTE"),
		("PISCINA"),
		("FRIGOBAR"),
		("RECEPÇÃO");

INSERT
	INTO
		DOCUMENTO_TIPO(NOME, DUPLICIDADE, VALIDADE, EXPEDITOR, EXPEDICAO)
	VALUES
		("CPF", 0, 0, 0, 0);