-- MySQL Script generated by MySQL Workbench
-- seg 20 mai 2019 20:41:26 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wghotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wghotel` ;

-- -----------------------------------------------------
-- Schema wghotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wghotel` DEFAULT CHARACTER SET utf8 ;
USE `wghotel` ;

-- -----------------------------------------------------
-- Table `wghotel`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`status` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `status_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`sexo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sexo_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`genero` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `genero_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`profissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`profissao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`profissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profissao_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `profissao_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `prenome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `nascimento` DATE NOT NULL,
  `sexo_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `profissao_id` INT NULL,
  `criacao` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_id_UNIQUE` (`id` ASC),
  INDEX `fk_status_id_pessoa_idx` (`status_id` ASC),
  INDEX `fk_sexo_id_pessoa_idx` (`sexo_id` ASC),
  INDEX `fk_genero_id_pessoa_idx` (`genero_id` ASC),
  INDEX `fk_profissao_id_pessoa_idx` (`profissao_id` ASC),
  CONSTRAINT `status_id_pessoa`
    FOREIGN KEY (`status_id`)
    REFERENCES `wghotel`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sexo_id_pessoa`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `wghotel`.`sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genero_id_pessoa`
    FOREIGN KEY (`genero_id`)
    REFERENCES `wghotel`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profissao_id_pessoa`
    FOREIGN KEY (`profissao_id`)
    REFERENCES `wghotel`.`profissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_tipo_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `pessoa_tipo_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`logradouro_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`logradouro_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`logradouro_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `logradouro_tipo_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pais` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `codigo_id` INT NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pais_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `pais_nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `pais_codigo_id_UNIQUE` (`codigo_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`estado` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estado_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `estado_nome_UNIQUE` (`nome` ASC),
  INDEX `fk_pais_id_estado_idx` (`pais_id` ASC),
  CONSTRAINT `pais_id_estado`
    FOREIGN KEY (`pais_id`)
    REFERENCES `wghotel`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`bairro` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`bairro` (
  `bairro_id` INT NOT NULL AUTO_INCREMENT,
  `bairro_nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`bairro_id`),
  UNIQUE INDEX `bairro_id_UNIQUE` (`bairro_id` ASC),
  INDEX `fk_estado_id_bairro_idx` (`estado_id` ASC),
  CONSTRAINT `estado_id_bairro`
    FOREIGN KEY (`estado_id`)
    REFERENCES `wghotel`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`logradouro` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`logradouro` (
  `logradouro_id` INT NOT NULL AUTO_INCREMENT,
  `logradouro_nome` VARCHAR(45) NOT NULL,
  `logradouro_tipo_id` INT NOT NULL,
  `bairro_id` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`logradouro_id`),
  UNIQUE INDEX `logradouro_id_UNIQUE` (`logradouro_id` ASC),
  UNIQUE INDEX `logradouro_nome_UNIQUE` (`logradouro_nome` ASC),
  INDEX `fk_logradouro_id_logradouro_idx` (`logradouro_tipo_id` ASC),
  INDEX `fk_bairro_id_logradouro_idx` (`bairro_id` ASC),
  CONSTRAINT `logradouro_tipo_id_logradouro`
    FOREIGN KEY (`logradouro_tipo_id`)
    REFERENCES `wghotel`.`logradouro_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bairro_id_logradouro`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `wghotel`.`bairro` (`bairro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`endereco_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`endereco_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`endereco_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `endereco_tipo_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `endereco_tipo_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_endereco` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `logradouro_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `endereco_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_endereco_id_UNIQUE` (`id` ASC),
  INDEX `fk_logradouro_id_pessoa_endereco_idx` (`logradouro_id` ASC),
  INDEX `fk_pessoa_id_pessoa_endereco_idx` (`pessoa_id` ASC),
  INDEX `fk_endereco_tipo_id_pessoa_endereco_idx` (`endereco_tipo_id` ASC),
  CONSTRAINT `logradouro_id_pessoa_endereco`
    FOREIGN KEY (`logradouro_id`)
    REFERENCES `wghotel`.`logradouro` (`logradouro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pessoa_id_pessoa_endereco`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `endereco_tipo_id_pessoa_endereco`
    FOREIGN KEY (`endereco_tipo_id`)
    REFERENCES `wghotel`.`endereco_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cidade` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_municipio_id` INT NOT NULL,
  `codigo_area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cidade_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cidade_nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `cidade_area_id_UNIQUE` (`codigo_area_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`documento_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`documento_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`documento_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `duplicidade` TINYINT(1) NOT NULL,
  `validade` TINYINT(1) NOT NULL,
  `expeditor` TINYINT(1) NOT NULL,
  `expedicao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_tipo_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `documento_tipo_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`orgao_expeditor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`orgao_expeditor` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`orgao_expeditor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `orgao_expeditor_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `orgao_expeditor_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_documento` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `documento_tipo_id` INT NOT NULL,
  `validade` DATE NULL,
  `expedicao` DATE NULL,
  `orgao_expeditor_id` INT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_documento_id_UNIQUE` (`id` ASC),
  INDEX `fk_pessoa_id_pessoa_documento_idx` (`pessoa_id` ASC),
  INDEX `fk_documento_tipo_id_pessoa_documento_idx` (`documento_tipo_id` ASC),
  INDEX `fk_orgao_expeditor_id_pessoa_documento_idx` (`orgao_expeditor_id` ASC),
  CONSTRAINT `pessoa_id_pessoa_documento`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_tipo_id_pessoa_documento`
    FOREIGN KEY (`documento_tipo_id`)
    REFERENCES `wghotel`.`documento_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orgao_expeditor_id_pessoa_documento`
    FOREIGN KEY (`orgao_expeditor_id`)
    REFERENCES `wghotel`.`orgao_expeditor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`telefone_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`telefone_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`telefone_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefone_tipo_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `telefone_tipo_nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_telefone` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(9) NOT NULL,
  `codigo_area_id` INT NOT NULL,
  `codigo_pais_id` INT NOT NULL,
  `telefone_tipo_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_telefone_id_UNIQUE` (`id` ASC),
  INDEX `fk_telefone_tipo_id_pessoa_telefone_idx` (`telefone_tipo_id` ASC),
  INDEX `fk_codigo_pais_id_pessoa_telefone_idx` (`codigo_pais_id` ASC),
  INDEX `fk_codigo_area_id_pessoa_telefone_idx` (`codigo_area_id` ASC),
  INDEX `fk_pessoa_id_pessoa_telefone_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_telefone_tipo_id_pessoa_telefone`
    FOREIGN KEY (`telefone_tipo_id`)
    REFERENCES `wghotel`.`telefone_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_pais_id_pessoa_telefone`
    FOREIGN KEY (`codigo_pais_id`)
    REFERENCES `wghotel`.`pais` (`codigo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_area_id_pessoa_telefone`
    FOREIGN KEY (`codigo_area_id`)
    REFERENCES `wghotel`.`cidade` (`codigo_area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_id_pessoa_telefone`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_pessoa_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_pessoa_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_pessoa_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `pessoa_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `pessoa_id_pessoa_pessoa_tipo_idx` (`pessoa_id` ASC),
  INDEX `pessoa_tipo_id_pessoa_pessoa_tipo_idx` (`pessoa_tipo_id` ASC),
  CONSTRAINT `pessoa_id_pessoa_pessoa_tipo`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pessoa_tipo_id_pessoa_pessoa_tipo`
    FOREIGN KEY (`pessoa_tipo_id`)
    REFERENCES `wghotel`.`pessoa_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cargo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`area` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cargo_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cargo_area` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cargo_area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `salario_min` DECIMAL(8,2) NOT NULL,
  `salario_max` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `cargo_id_cargo_area_idx` (`cargo_id` ASC),
  INDEX `area_id_cargo_area_idx` (`area_id` ASC),
  CONSTRAINT `cargo_id_cargo_area`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `wghotel`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `area_id_cargo_area`
    FOREIGN KEY (`area_id`)
    REFERENCES `wghotel`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`saida_motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`saida_motivo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`saida_motivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`funcionario_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`funcionario_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`funcionario_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `cargo_area_id` INT NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL,
  `contratacao` DATE NOT NULL,
  `demissao` DATE NULL,
  `saida_motivo_id` INT NULL,
  `funcionario_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `pessoa_id_funcionario_idx` (`pessoa_id` ASC),
  INDEX `cargo_area_id_funcionario_idx` (`cargo_area_id` ASC),
  INDEX `saida_motivo_id_funcionario_idx` (`saida_motivo_id` ASC),
  INDEX `funcionario_tipo_id_funcionario_idx` (`funcionario_tipo_id` ASC),
  CONSTRAINT `pessoa_id_funcionario`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo_area_id_funcionario`
    FOREIGN KEY (`cargo_area_id`)
    REFERENCES `wghotel`.`cargo_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saida_motivo_id_funcionario`
    FOREIGN KEY (`saida_motivo_id`)
    REFERENCES `wghotel`.`saida_motivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `funcionario_tipo_id_funcionario`
    FOREIGN KEY (`funcionario_tipo_id`)
    REFERENCES `wghotel`.`funcionario_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`funcionario_promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`funcionario_promocao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`funcionario_promocao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT NOT NULL,
  `cargo_area_id` INT NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cliente` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `pessoa_id_cliente_idx` (`pessoa_id` ASC),
  CONSTRAINT `pessoa_id_cliente`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`grupo_fidelidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`grupo_fidelidade` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`grupo_fidelidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cliente_fidelidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cliente_fidelidade` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cliente_fidelidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `grupo_fidelidade_id` INT NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `cliente_id_cliente_fidelidade_idx` (`cliente_id` ASC),
  INDEX `grupo_fidelidade_id_cliente_fidelidade_idx` (`grupo_fidelidade_id` ASC),
  CONSTRAINT `cliente_id_cliente_fidelidade`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `wghotel`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_fidelidade_id_cliente_fidelidade`
    FOREIGN KEY (`grupo_fidelidade_id`)
    REFERENCES `wghotel`.`grupo_fidelidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`beneficio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`beneficio` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`beneficio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`grupo_fidelidade_beneficio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`grupo_fidelidade_beneficio` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`grupo_fidelidade_beneficio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_fidelidade_id` INT NOT NULL,
  `beneficio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `grupo_fidelidade_id_grupo_fidelidade_beneficio_idx` (`grupo_fidelidade_id` ASC),
  INDEX `beneficio_id_grupo_fidelidade_beneficio_idx` (`beneficio_id` ASC),
  CONSTRAINT `grupo_fidelidade_id_grupo_fidelidade_beneficio`
    FOREIGN KEY (`grupo_fidelidade_id`)
    REFERENCES `wghotel`.`grupo_fidelidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `beneficio_id_grupo_fidelidade_beneficio`
    FOREIGN KEY (`beneficio_id`)
    REFERENCES `wghotel`.`beneficio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `andar` INT NOT NULL,
  `acomodacao_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_tipo_id_acomodacao_idx` (`acomodacao_tipo_id` ASC),
  CONSTRAINT `acomodacao_tipo_id_acomodacao`
    FOREIGN KEY (`acomodacao_tipo_id`)
    REFERENCES `wghotel`.`acomodacao_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`mobilia_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`mobilia_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`mobilia_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`fabricante` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`fabricante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`mobilia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`mobilia` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`mobilia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `mobilia_tipo_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `status_id` INT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `fabricante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `mobilia_tipo_id_mobilia_idx` (`mobilia_tipo_id` ASC),
  INDEX `fabricante_id_mobilia_idx` (`fabricante_id` ASC),
  CONSTRAINT `mobilia_tipo_id_mobilia`
    FOREIGN KEY (`mobilia_tipo_id`)
    REFERENCES `wghotel`.`mobilia_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fabricante_id_mobilia`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `wghotel`.`fabricante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_cama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_cama` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_cama` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_id` INT NOT NULL,
  `mobilia_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_id_acomodacao_cama_idx` (`acomodacao_id` ASC),
  INDEX `mobilia_id_acomodacao_cama_idx` (`mobilia_id` ASC),
  CONSTRAINT `acomodacao_id_acomodacao_cama`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mobilia_id_acomodacao_cama`
    FOREIGN KEY (`mobilia_id`)
    REFERENCES `wghotel`.`mobilia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_mobilia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_mobilia` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_mobilia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_id` INT NOT NULL,
  `mobilia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_id_acomodacao_mobilia_idx` (`acomodacao_id` ASC),
  INDEX `mobilia_id_acomodacao_mobilia_idx` (`mobilia_id` ASC),
  CONSTRAINT `acomodacao_id_acomodacao_mobilia`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mobilia_id_acomodacao_mobilia`
    FOREIGN KEY (`mobilia_id`)
    REFERENCES `wghotel`.`mobilia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`reserva` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `cliente_id_reserva_idx` (`cliente_id` ASC),
  INDEX `status_id_reserva_idx` (`status_id` ASC),
  UNIQUE INDEX `cliente_id_UNIQUE` (`cliente_id` ASC),
  CONSTRAINT `cliente_id_reserva`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `wghotel`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id_reserva`
    FOREIGN KEY (`status_id`)
    REFERENCES `wghotel`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`permissao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`funcionario_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`funcionario_permissao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`funcionario_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissao_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `funcionario_id_funcionario_permissao_idx` (`funcionario_id` ASC),
  INDEX `permissao_funcionario_permissao_idx` (`permissao_id` ASC),
  CONSTRAINT `funcionario_id_funcionario_permissao`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `wghotel`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `permissao_funcionario_permissao`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `wghotel`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`estadia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`estadia` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`estadia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` INT NULL,
  `comentario` VARCHAR(500) NULL,
  `checkin` DATETIME NOT NULL,
  `checkout` DATETIME NULL,
  `snapshot` JSON NOT NULL,
  `reserva_id` INT NULL,
  `status_id` INT NOT NULL,
  `acomodacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `status_id_estadia_idx` (`status_id` ASC),
  INDEX `acomodacao_id_estadia_idx` (`acomodacao_id` ASC),
  INDEX `reserva_id_estadia_idx` (`reserva_id` ASC),
  CONSTRAINT `status_id_estadia`
    FOREIGN KEY (`status_id`)
    REFERENCES `wghotel`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acomodacao_id_estadia`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reserva_id_estadia`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `wghotel`.`reserva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`grupo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_grupo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `acomodacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `grupo_id_acomodacao_grupo_idx` (`grupo_id` ASC),
  INDEX `acomodacao_id_acomodacao_grupo_idx` (`acomodacao_id` ASC),
  CONSTRAINT `grupo_id_acomodacao_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `wghotel`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acomodacao_id_acomodacao_grupo`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`reserva_acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`reserva_acomodacao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`reserva_acomodacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_grupo_id` INT NULL,
  `reserva_id` INT NOT NULL,
  `acomodacao_tipo` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `reserva_id_reserva_acomodacao_idx` (`reserva_id` ASC),
  INDEX `acomodacao_grupo_id_reserva_acomodacao_idx` (`acomodacao_grupo_id` ASC),
  INDEX `acomodacao_tipo_reserva_acomodacao_idx` (`acomodacao_tipo` ASC),
  CONSTRAINT `reserva_id_reserva_acomodacao`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `wghotel`.`reserva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acomodacao_grupo_id_reserva_acomodacao`
    FOREIGN KEY (`acomodacao_grupo_id`)
    REFERENCES `wghotel`.`acomodacao_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acomodacao_tipo_reserva_acomodacao`
    FOREIGN KEY (`acomodacao_tipo`)
    REFERENCES `wghotel`.`acomodacao_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`fatura` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`fatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(8,2) NOT NULL,
  `status_id` INT NOT NULL,
  `estadia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `status_id_fatura_idx` (`status_id` ASC),
  INDEX `estadia_id_fatura_idx` (`estadia_id` ASC),
  CONSTRAINT `status_id_fatura`
    FOREIGN KEY (`status_id`)
    REFERENCES `wghotel`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estadia_id_fatura`
    FOREIGN KEY (`estadia_id`)
    REFERENCES `wghotel`.`estadia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`transacao_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`transacao_tipo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`transacao_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`transacao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`transacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `transacao_tipo_id` INT NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `transacao_tipo_id_UNIQUE` (`transacao_tipo_id` ASC),
  INDEX `funcionario_id_transacao_idx` (`funcionario_id` ASC),
  CONSTRAINT `funcionario_id_transacao`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `wghotel`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transacao_tipo_transacao`
    FOREIGN KEY (`transacao_tipo_id`)
    REFERENCES `wghotel`.`transacao_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`fatura_transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`fatura_transacao` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`fatura_transacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fatura_id` INT NOT NULL,
  `transacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fatura_id_fatura_transacao_idx` (`fatura_id` ASC),
  INDEX `transacao_id_fatura_transacao_idx` (`transacao_id` ASC),
  CONSTRAINT `fatura_id_fatura_transacao`
    FOREIGN KEY (`fatura_id`)
    REFERENCES `wghotel`.`fatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transacao_id_fatura_transacao`
    FOREIGN KEY (`transacao_id`)
    REFERENCES `wghotel`.`transacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`ambiente` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`ambiente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_ambiente` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_ambiente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_id` INT NOT NULL,
  `ambiente_id` INT NOT NULL,
  `tamanho` DECIMAL(5,1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_id_acomodacao_ambiente_idx` (`acomodacao_id` ASC),
  INDEX `ambiente_acomodacao_ambiente_idx` (`ambiente_id` ASC),
  CONSTRAINT `acomodacao_id_acomodacao_ambiente`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ambiente_acomodacao_ambiente`
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `wghotel`.`ambiente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`item_fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`item_fatura` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`item_fatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `quantidade` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `fatura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fatura_id_item_fatura_idx` (`fatura_id` ASC),
  CONSTRAINT `fatura_id_item_fatura`
    FOREIGN KEY (`fatura_id`)
    REFERENCES `wghotel`.`fatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`item` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`origem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`origem` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`consumo_estadia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`consumo_estadia` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`consumo_estadia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estadia_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `origem_id` INT NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `estadia_id_consumo_estadia_idx` (`estadia_id` ASC),
  INDEX `item_id_consumo_estadia_idx` (`item_id` ASC),
  INDEX `origem_id_consumo_estadia_idx` (`origem_id` ASC),
  CONSTRAINT `estadia_id_consumo_estadia`
    FOREIGN KEY (`estadia_id`)
    REFERENCES `wghotel`.`estadia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id_consumo_estadia`
    FOREIGN KEY (`item_id`)
    REFERENCES `wghotel`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `origem_id_consumo_estadia`
    FOREIGN KEY (`origem_id`)
    REFERENCES `wghotel`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`veiculo_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`veiculo_modelo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`veiculo_modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fabricante_id` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fabricante_id_veiculo_modelo_idx` (`fabricante_id` ASC),
  CONSTRAINT `fabricante_id_veiculo_modelo`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `wghotel`.`fabricante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`cor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`cor` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`cor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `veiculo_modelo_id` INT NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `cor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `veiculo_modelo_id_veiculo_idx` (`veiculo_modelo_id` ASC),
  INDEX `cor_id_veiculo_idx` (`cor_id` ASC),
  CONSTRAINT `veiculo_modelo_id_veiculo`
    FOREIGN KEY (`veiculo_modelo_id`)
    REFERENCES `wghotel`.`veiculo_modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cor_id_veiculo`
    FOREIGN KEY (`cor_id`)
    REFERENCES `wghotel`.`cor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`pessoa_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`pessoa_veiculo` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`pessoa_veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `pessoa_id_pessoa_veiculo_idx` (`pessoa_id` ASC),
  INDEX `veiculo_id_pessoa_veiculo_idx` (`veiculo_id` ASC),
  CONSTRAINT `pessoa_id_pessoa_veiculo`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `veiculo_id_pessoa_veiculo`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `wghotel`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`veiculo_acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`veiculo_acesso` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`veiculo_acesso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `acesso_tipo_id` INT NOT NULL,
  `acesso_modo_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `veiculo_id_veiculo_acesso_idx` (`veiculo_id` ASC),
  CONSTRAINT `veiculo_id_veiculo_acesso`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `wghotel`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_acesso` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_acesso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_id_acomodacao_acesso_idx` (`acomodacao_id` ASC),
  INDEX `pessoa_id_acomodacao_acesso_idx` (`pessoa_id` ASC),
  CONSTRAINT `acomodacao_id_acomodacao_acesso`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `wghotel`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pessoa_id_acomodacao_acesso`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `wghotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`acomodacao_limpeza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`acomodacao_limpeza` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`acomodacao_limpeza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_acesso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `acomodacao_acesso_id_acomodacao_limpeza_idx` (`acomodacao_acesso_id` ASC),
  CONSTRAINT `acomodacao_acesso_id_acomodacao_limpeza`
    FOREIGN KEY (`acomodacao_acesso_id`)
    REFERENCES `wghotel`.`acomodacao_acesso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`transacao_boleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`transacao_boleto` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`transacao_boleto` (
  `id` INT NOT NULL,
  `transacao_id` INT NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `vencimento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `transacao_id_transacao_boleto_idx` (`transacao_id` ASC),
  CONSTRAINT `transacao_id_transacao_boleto`
    FOREIGN KEY (`transacao_id`)
    REFERENCES `wghotel`.`transacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wghotel`.`estadia_acompanhante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wghotel`.`estadia_acompanhante` ;

CREATE TABLE IF NOT EXISTS `wghotel`.`estadia_acompanhante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estadia_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `estadia_id_estadia_acompanhante_idx` (`estadia_id` ASC),
  INDEX `cliente_id_estadia_acompanhante_idx` (`cliente_id` ASC),
  CONSTRAINT `estadia_id_estadia_acompanhante`
    FOREIGN KEY (`estadia_id`)
    REFERENCES `wghotel`.`estadia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_id_estadia_acompanhante`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `wghotel`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
